//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Obrabiarka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Frezarki_5_osiowe
    {
        public int Id { get; set; }
        public string Nazwa { get; set; }
        public string X { get; set; }
        public string Y { get; set; }
        public string Z { get; set; }
        public bool Rezerwuj { get; set; }
    }
}
