//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Obrabiarka
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ContactDBEntities1 : DbContext
    {
        public ContactDBEntities1()
            : base("name=ContactDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Frezarki_3_osiowe> Frezarki_3_osiowe { get; set; }
        public virtual DbSet<Frezarki_4_osiowe_z_napedzanym_narzedziem> Frezarki_4_osiowe_z_napedzanym_narzedziem { get; set; }
        public virtual DbSet<Frezarki_5_osiowe> Frezarki_5_osiowe { get; set; }
        public virtual DbSet<Frezy_palcowe> Frezy_palcowes { get; set; }
        public virtual DbSet<Frezy_tarczowe> Frezy_tarczowes { get; set; }
        public virtual DbSet<Narzedzia> Narzedzias { get; set; }
        public virtual DbSet<Narzedzia_tokarskie_lewe> Narzedzia_tokarskie_lewes { get; set; }
        public virtual DbSet<Narzedzia_tokarskie_prawe> Narzedzia_tokarskie_prawes { get; set; }
        public virtual DbSet<Obrabiarki> Obrabiarkis { get; set; }
        public virtual DbSet<Operacje> Operacjes { get; set; }
        public virtual DbSet<RodzajeNarzedzi> RodzajeNarzedzis { get; set; }
        public virtual DbSet<RodzajeObrabiarek> RodzajeObrabiareks { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Szlifierki_bezklowe> Szlifierki_bezklowes { get; set; }
        public virtual DbSet<Szlifierki_klowe> Szlifierki_klowes { get; set; }
        public virtual DbSet<Tokarki_karuzelowe> Tokarki_karuzelowes { get; set; }
        public virtual DbSet<Tokarki_poziome> Tokarki_poziomes { get; set; }
        public virtual DbSet<Tokarki_XZ> Tokarki_XZs { get; set; }
        public virtual DbSet<Tokarki_XZC_z_napedzanym_narzedziem> Tokarki_XZC_z_napedzanym_narzedziems { get; set; }
        public virtual DbSet<Wiertarki_CNC> Wiertarki_CNCs { get; set; }
        public virtual DbSet<Wiertarki_reczne> Wiertarki_recznes { get; set; }
        public virtual DbSet<Wiertla_pelnoweglikowe> Wiertla_pelnoweglikowes { get; set; }
        public virtual DbSet<Wiertla_skladane> Wiertla_skladanes { get; set; }
        public virtual DbSet<Wytaczaki_tokarskie_hakowe> Wytaczaki_tokarskie_hakowes { get; set; }
        public virtual DbSet<Wytaczaki_tokarskie_proste> Wytaczaki_tokarskie_prostes { get; set; }
        public virtual DbSet<Wytaczaki_tokarskie_spiczaste> Wytaczaki_tokarskie_spiczastes { get; set; }
        public virtual DbSet<Zabiegi> Zabiegis { get; set; }
    }
}
