//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Obrabiarka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Narzedzia_tokarskie_lewe
    {
        public int id { get; set; }
        public string Nazwa_narzędzia { get; set; }
        public Nullable<double> D { get; set; }
        public bool Rezerwuj { get; set; }
    }
}
