//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Obrabiarka
{
    using System;
    using System.Collections.Generic;
    
    public partial class RodzajeObrabiarek
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RodzajeObrabiarek()
        {
            this.Operacjes = new HashSet<Operacje>();
        }
    
        public int id_rodzajeobrabiarek { get; set; }
        public string rodzaj_obrabiarki { get; set; }
        public Nullable<int> id_obrabiarki { get; set; }
    
        public virtual Obrabiarki Obrabiarki { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Operacje> Operacjes { get; set; }
    }
}
