//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Obrabiarka
{
    using System;
    using System.Collections.Generic;
    
    public partial class RodzajeNarzedzi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RodzajeNarzedzi()
        {
            this.Zabiegis = new HashSet<Zabiegi>();
        }
    
        public int id_rodzajenarzedzi { get; set; }
        public Nullable<int> id_narzedzia { get; set; }
        public string rodzaj_narzedzia { get; set; }
    
        public virtual Narzedzia Narzedzia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zabiegi> Zabiegis { get; set; }
    }
}
