//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Obrabiarka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tokarki_poziome
    {
        public int id { get; set; }
        public string Nazwa { get; set; }
        public Nullable<int> Max__średnica_toczenia { get; set; }
        public Nullable<int> Max__długość_toczenia { get; set; }
        public bool Rezerwuj { get; set; }
    }
}
