//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Obrabiarka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zabiegi
    {
        public int id_zabiegu { get; set; }
        public string nazwa_zabiegu { get; set; }
        public Nullable<int> id_rodzajenarzedzi { get; set; }
    
        public virtual RodzajeNarzedzi RodzajeNarzedzi { get; set; }
    }
}
